#!/bin/sh

unset GIT_DIR

CURRENT=`date +%Y-%m-%d-%H-%M-%S` &&
cd /home/ncr/apps/flickr_spy &&
git clone /home/ncr/repos/flickr_spy $CURRENT &&
cd $CURRENT &&
git submodule init &&
git submodule update &&
cd .. &&
ln -sfT $CURRENT current &&
sudo stop flickr-spy &&
sudo start flickr-spy &&
echo ok || echo fail
